### ISSUE TITLE
overwriting other presets need lockdown(1.10.2)

### ISSUE THREAD

**Issue by SDUBZ** [Adubbz/Lockdown#13]
when i try using Yunomakegoodmap/garden of glass with lockdown it overwrites there gen and uses the template instead but if i set Disable Regular World Creation"=false it doesnt load template i think compatability needs to be added when these mods are used together

**Comment by Adubbz** [comment]
What you've just described sounds like normal functionality... The template world should be created with that worldtype to begin with, otherwise it won't work.
