### ISSUE TITLE
[1.12.1] [7.0.1] Unable create new world

### ISSUE THREAD

**Issue by GWSheridan** [Adubbz/Lockdown#17]
Versions
Minecraft 1.12.1
Forge-14.22.1.2484
Lockdown-1.12.1-7.0.1-universal

When have these setting enabled in the mod
You are unable to create new world as will take you back to main menu

"main menu" {
    B:"Disable Multiplayer Button"=false
    B:"Disable Singleplayer Button"=false
}

"world creation" {
    B:"Disable Game Mode Button"=true
    B:"Disable More World Options Button"=true
    B:"Disable Regular World Creation"=true
    B:"Enable Overriding Template World Settings"=false
    S:"World Template Directory"=template
}

**Comment by Adubbz** [comment]
It sounds like you've tried to create a world without a template, and have enabled disabling regular world creation. This is functioning as intended.
