### ISSUE TITLE
Game mode Button disabled

### ISSUE THREAD

**Issue by BlakeDarwinXE** [Adubbz/Lockdown#6]
If you set B:"Disable Game Mode Button"=false players are not able to create a create new worlds in created mod.

But you are able to create a Create world if you set "Disable Regular World Creation" to false.

Version: Lockdown-universal-1.7.2-2.0.0.0
Forge: 10.13.4.1492
File: Lockdown.cfg

Config:
 # Configuration file

"main menu" {
    B:"Disable Multiplayer Button"=false
}

"world creation" {
    B:"Disable Game Mode Button"=false
    B:"Disable More World Options Button"=true
    B:"Disable Regular World Creation"=true
    S:"World Template Directory"=template
}

**Comment by Adubbz** [comment]
This is functioning as expected. Disabling the gamemode button is purely a visual thing and is not intended to allow players to create worlds normally. If that is desired the 'disable regular world creation' should be used, or you should exclude the save files for the overworld from the template. If you do this and leave the game mode button enabled, the overworld will be generated using those settings as normal (I haven't made a release with these changes yet though, they were from a PR that was merged)
