### ISSUE TITLE
[Request] Enabling default terrain generation while still allowing Lockdown

### ISSUE THREAD

**Issue by rockobonaparte** [Adubbz/Lockdown#7]
I am hoping to have Lockdown start in a different dimension that I keep in the template directory, but fall back to user-defined settings for the Overworld generation. So the template would have, say, a DIM2 folder where the player's position has been saved, but the Overworld region folder is gone. When a new world is started, they'd start in DIM2, and when sent to the overworld spawn (courtesy of my own code), it will go to the spawn of the overworld they have specified when creating a new world.

Context:
I am trying to use Lockdown for my modpack, Baby's First Space Race. It is a tutorial mod pack where I want to allow players to stumble around the Overworld however they want, but I'd want them to start in a tutorial dimension that they can regularly access to see how certain things are done. Examples of these things are building the smeltery, how to work with Big Reactor, advanced ore processing, and farming.

I'd like them to start in this world particularly because beginners have complained that it's usually past nighttime when they have read the quest book and figured out what they're supposed to be doing, and then they get blown away by the regular night-time mobs.

I have built a suitable dimension using RFTools, and it is saved at DIM2. I can then set up the template folder, and delete the /region folder defining the Overworld. The problem is that when they go to the Overworld, it generates according to the settings I used in the original save, not what I asserted on startup. I know this as a fact since I created the save using a flat world, but I specified a different terrain generator when creating the new world.

I was assuming then that setting "Disable Regular World Creation" to false would bypass this, but it appears to just shut off Lockdown completely. Is there a way to keep lockdown enabled while still allowing user-defined world creation?

**Comment by rockobonaparte** [comment]
I suppose I should mention the mod pack is still targeting 1.7.10. If I must, I can attempt to backport some fix for my personal reasons.

**Comment by Adubbz** [comment]
Hrm, this isn't something which is currently implemented in the mod. In its essence, Lockdown simply copies, pastes and loads worlds with some extra gui disabling features thrown in. I'd imagine changing world settings after initial setup is possible, although it seems like it would have a small amount of use cases and will almost certainly cause seams with any pre-existing chunks. I wouldn't rule it out, but i'm curious how much demand there is for this sort of thing

**Comment by rockobonaparte** [comment]
The original overworld region files from the save are gone in the template.
It would be a fresh regeneration using the settings the end user supplied,
versus what I used originally in the first save.

**Comment by Adubbz** [comment]
If this were to be implemented, it would only generate new chunks using the new settings provided *not* regenerate old ones. Achieving a random 'fresh' Overworld would still require deleting its files. Adding artificial restrictions by requiring the entire world to be regenerated is silly, however I was pointing out that there will be seams if it is used with worlds that aren't 'fresh'.

**Comment by rockobonaparte** [comment]
It would definitely have to be an option. I had looked at Blightfall before
and it was using a custom Overworld, so regions not previously generated
would be affected if they went out of the accepted boundaries of the game
world. For what I'm doing, I'm just deleting the whole Overworld before
setting it up as Lockdown's template.

**Comment by rockobonaparte** [comment]
I'm poking at this myself, but I'm not verify proficient in Forge myself yet. It looks like if you created a WorldSettings instance and fed that into launchIntegratedServer() instead of a null handle, it would at least receive the information the player gave. I don't know if it would stick, but it would be a start. I'm guessing if you can't look at it any time soon, I can try to see where in Lockdown's history it last was 1.7.10 and try to mimic vanilla Minecraft's code for initializing WorldSettings.

**Comment by rockobonaparte** [comment]
I have a 1.7 topic branch where I managed to implement this:
https://github.com/rockobonaparte/Lockdown/tree/override_terrain_gen_1.7

I am planning to use this in BFSR. Do you want me to send it in to you with a pull request?

**Comment by Adubbz** [comment]
Yeah, go right ahead. I took a look over the commit and it seems you were thinking the same thing I was (despite being slightly confused at what you were originally asking). The implementation looks good to me :+1:
